import { Car } from '@/types/car';

export const cars: Car[] = [
  {
    id: '1',
    name: 'Explorer Pro',
    brand: 'Ford',
    category: 'SUV',
    seats: 7,
    pricePerDay: 89,
    transmission: 'Auto',
    imageUrl: '/suv.png',
    shortDescription: 'A spacious and powerful SUV perfect for family adventures.',
    longDescription: 'The Ford Explorer Pro is built for those who demand both comfort and capability. With three rows of seating and a turbocharged engine, it handles everything from city streets to rugged trails with ease. Packed with modern safety features and a premium interior, it is the ultimate family vehicle.',
    features: ['3-row seating', 'Apple CarPlay & Android Auto', 'Adaptive cruise control', 'Heated front seats', 'Panoramic sunroof', 'Blind spot monitoring', 'Rear camera'],
    available: true,
  },
  {
    id: '2',
    name: 'Civic Elegance',
    brand: 'Honda',
    category: 'Sedan',
    seats: 5,
    pricePerDay: 55,
    transmission: 'Auto',
    imageUrl: 'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=800&q=80',
    shortDescription: 'A refined and fuel-efficient sedan for every journey.',
    longDescription: 'The Honda Civic Elegance combines sleek styling with exceptional fuel economy and a comfortable ride. Ideal for business travelers and city drivers, it offers a quiet cabin, intuitive tech features, and precise handling. A smart, reliable choice for any occasion.',
    features: ['Wireless charging', 'Honda Sensing safety suite', 'Heated seats', 'LED headlights', 'Touchscreen display', 'Lane keeping assist', 'Remote start'],
    available: true,
  },
  {
    id: '3',
    name: 'Model S Plaid',
    brand: 'Tesla',
    category: 'Electric',
    seats: 5,
    pricePerDay: 149,
    transmission: 'Auto',
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80',
    shortDescription: 'Blazing-fast electric performance with cutting-edge technology.',
    longDescription: 'The Tesla Model S Plaid redefines what a car can be. With a 0–60 mph time of under 2 seconds and a range exceeding 390 miles, it is the pinnacle of electric performance. The 17-inch touchscreen, over-the-air updates, and Autopilot make every drive an experience to remember.',
    features: ['Autopilot', '17" touchscreen', '390+ mile range', 'Over-the-air updates', 'Gaming capability', 'Premium audio system', 'Dog mode'],
    available: true,
  },
  {
    id: '4',
    name: '911 Carrera S',
    brand: 'Porsche',
    category: 'Convertible',
    seats: 2,
    pricePerDay: 249,
    transmission: 'Auto',
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80',
    shortDescription: 'An iconic convertible delivering pure driving thrills.',
    longDescription: 'The Porsche 911 Carrera S Cabriolet is the ultimate expression of sports car engineering. Drop the top and feel the wind as the flat-six engine roars behind you. Precise steering, world-class brakes, and a beautifully crafted interior make this an unforgettable driving experience.',
    features: ['Retractable soft top', 'Sport Chrono Package', 'BOSE surround sound', 'Sport exhaust', 'Heated leather seats', 'Park assist', 'Night vision assist'],
    available: true,
  },
  {
    id: '5',
    name: 'Kona Electric',
    brand: 'Hyundai',
    category: 'Electric',
    seats: 5,
    pricePerDay: 79,
    transmission: 'Auto',
    imageUrl: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&q=80',
    shortDescription: 'Affordable electric crossover with impressive range.',
    longDescription: 'The Hyundai Kona Electric is an accessible gateway into electric driving without compromising on practicality. With up to 258 miles of range and a roomy cabin, it is perfect for daily commutes and weekend getaways alike. Fast charging capability means less time waiting and more time driving.',
    features: ['258-mile range', 'Fast charging support', 'Bluelink connectivity', 'Smart cruise control', '10.25" navigation display', 'Vehicle-to-load (V2L)', 'One-pedal driving'],
    available: true,
  },
  {
    id: '6',
    name: 'Mustang GT',
    brand: 'Ford',
    category: 'Convertible',
    seats: 4,
    pricePerDay: 129,
    transmission: 'Manual',
    imageUrl: 'https://images.unsplash.com/photo-1547744152-14d985cb937f?w=800&q=80',
    shortDescription: 'Classic American muscle with open-air excitement.',
    longDescription: 'The Ford Mustang GT Convertible is an American icon that never gets old. With a 5.0L V8 engine producing 450 horsepower, it delivers thrilling acceleration with an unforgettable exhaust note. Drop the top and cruise in style — this is driving at its most pure and exciting.',
    features: ['5.0L V8 engine', 'Convertible soft top', 'SYNC 4 infotainment', 'B&O audio system', 'Selectable drive modes', 'Track apps', 'Launch control'],
    available: true,
  },
  {
    id: '7',
    name: 'X5 xDrive',
    brand: 'BMW',
    category: 'SUV',
    seats: 5,
    pricePerDay: 159,
    transmission: 'Auto',
    imageUrl: '/suv.png',
    shortDescription: 'Luxurious SUV blending performance with premium comfort.',
    longDescription: 'The BMW X5 xDrive combines athletic performance with ultimate luxury. Its turbocharged inline-6 engine delivers effortless power, while the air suspension soaks up road imperfections. Inside, the iDrive system, panoramic roof, and hand-stitched leather create a truly premium environment.',
    features: ['Air suspension', 'iDrive 8 system', 'Panoramic sky lounge', 'Harman Kardon audio', 'Gesture control', 'Heads-up display', 'Active park assist'],
    available: true,
  },
  {
    id: '8',
    name: 'Camry Hybrid',
    brand: 'Toyota',
    category: 'Sedan',
    seats: 5,
    pricePerDay: 65,
    transmission: 'Auto',
    imageUrl: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80',
    shortDescription: 'Reliable hybrid sedan with outstanding fuel economy.',
    longDescription: 'The Toyota Camry Hybrid is the benchmark for reliability and efficiency in the midsize sedan segment. With its proven hybrid powertrain delivering up to 52 MPG combined, you can go further for less. A spacious, quiet cabin and Toyota Safety Sense make it a top choice for long-distance travel.',
    features: ['52 MPG combined', 'Toyota Safety Sense 2.5+', 'JBL audio system', 'Wireless Apple CarPlay', 'Digital instrument cluster', 'Radar cruise control', 'Automatic emergency braking'],
    available: false,
  },
];
